name: Continuos Deploy

on:
  workflow_run:
    workflows: ["Continuos Integration"]
    branches: [main]
    type:
      - completed

jobs:
  deploy_app:
    runs-on: ubuntu-latest
    steps:
      - name: Realiza o checkout
        uses: actions/checkout@v2
      
      - name: Project Django
        run: cd django_linkedlist/

      - name: Deploy no Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "iadev"
          heroku_email:  ${{secrets.EMAIL}}